#!/usr/bin/env python3
"""
Generiert CSV-Dateien für die Lengo-Vokabelapp aus Moritz' Klassen-Notizen.
Format: Portugiesisch;Deutsch;Notiz/Beispiel
Encoding: UTF-8 mit BOM (für bessere Mobile-Kompatibilität)
"""
import csv
import os

OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))

# Karten pro Lesson: (PT, DE, Notiz)
LESSONS = {
    "lesson-01": {
        "title": "Lesson 1 — Vorstellung & Pronomen (05.03.2026)",
        "cards": [
            ("Bom dia", "Guten Morgen / Guten Tag", "Begrüßung"),
            ("Olá", "Hallo", ""),
            ("Eu sou", "Ich bin", "ser"),
            ("Sou da Alemanha", "Ich komme aus Deutschland", ""),
            ("Vivo em Frankfurt", "Ich wohne in Frankfurt", "viver"),
            ("Moro em Frankfurt", "Ich wohne in Frankfurt", "morar"),
            ("Tenho 28 anos", "Ich bin 28 Jahre alt", "ter (haben für Alter!)"),
            ("Sou empreendedor", "Ich bin Unternehmer", ""),
            ("Gosto de", "Ich mag", "+ Verb oder Substantiv"),
            ("Não gosto de", "Ich mag nicht", ""),
            ("Trabalho com", "Ich arbeite mit", ""),
            ("Trabalho como", "Ich arbeite als", ""),
            ("Preguiça", "Faulheit", "Substantiv"),
            ("Preguiçoso", "faul (m)", "Adjektiv männlich"),
            ("Preguiçosa", "faul (w)", "Adjektiv weiblich"),
            ("O que mais?", "Was noch?", "Frage"),
            ("Meu nome é", "Mein Name ist", ""),
            ("Chamo-me", "Ich heiße", "reflexiv"),
            ("Como te chamas?", "Wie heißt du?", "informell, reflexiv"),
            ("Qual é o seu nome?", "Wie ist Ihr Name?", "formell"),
            ("Qual é a sua cidade preferida?", "Was ist deine Lieblingsstadt?", ""),
            ("Onde moras?", "Wo wohnst du?", ""),
            ("Onde vives?", "Wo lebst du?", ""),
            ("Quem te recomendou a mim?", "Wer hat dich mir empfohlen?", ""),
            ("Quando vais para Portugal?", "Wann fährst du nach Portugal?", ""),
            ("O que é um carro elétrico?", "Was ist ein Elektroauto?", ""),
            ("Que negócio queres fazer?", "Was für ein Geschäft willst du machen?", ""),
            ("Porquê?", "Warum?", ""),
            ("Quantos anos tens?", "Wie alt bist du?", ""),
            ("Eu", "ich", "Pronomen"),
            ("Tu", "du", "Pronomen (informell)"),
            ("Ele", "er", ""),
            ("Ela", "sie", ""),
            ("Você", "Sie / du (BR)", "formell PT, du in BR"),
            ("Nós", "wir", ""),
            ("Eles", "sie (m. oder gemischt)", ""),
            ("Elas", "sie (nur weiblich)", ""),
            ("Vocês", "ihr / Sie (Plural)", ""),
            ("gostar", "mögen", "Verb"),
            ("trabalhar", "arbeiten", "Verb -ar"),
            ("ter", "haben", "Verb unregelmäßig"),
            ("viver", "leben", "Verb -er"),
            ("viajar", "reisen", "Verb -ar"),
            ("pessoas", "Personen / Menschen", ""),
            ("preparar", "vorbereiten", ""),
            ("esperar", "warten", ""),
            ("cidade", "Stadt", ""),
            ("para", "für / zum / nach", "Präposition"),
            ("o pintor / a pintora", "Maler / Malerin", "Beruf"),
            ("o cantor / a cantora", "Sänger / Sängerin", ""),
            ("o tradutor / a tradutora", "Übersetzer / Übersetzerin", ""),
            ("o médico / a médica", "Arzt / Ärztin", ""),
            ("o advogado / a advogada", "Anwalt / Anwältin", ""),
            ("o cabeleireiro / a cabeleireira", "Friseur / Friseurin", ""),
            ("o jornalista / a jornalista", "Journalist (gleich m/f)", ""),
            ("o dentista / a dentista", "Zahnarzt (gleich m/f)", ""),
            ("o motorista / a motorista", "Fahrer (gleich m/f)", ""),
            ("o estudante / a estudante", "Student (gleich m/f)", ""),
            ("Onde fica a casa de banho?", "Wo ist die Toilette?", "praktische Frage"),
        ]
    },
    "lesson-02": {
        "title": "Lesson 2 — Estar, Estado civil, Zahlen (12.03.2026)",
        "cards": [
            ("Estou um pouco cansado", "Ich bin ein bisschen müde", "estar"),
            ("Também estou cansado", "Ich bin auch müde", ""),
            ("Casado / Casada", "verheiratet", "Estado civil"),
            ("Solteiro / Solteira", "ledig", ""),
            ("Divorciado / Divorciada", "geschieden", ""),
            ("Viúvo / Viúva", "verwitwet", ""),
            ("Qual é a profissão de...?", "Was ist der Beruf von...?", ""),
            ("Quantos anos tem?", "Wie alt ist er/sie?", ""),
            ("Que idade tem?", "Welches Alter hat er/sie?", "alternative Frage"),
            ("Qual é o número de telefone?", "Wie ist die Telefonnummer?", ""),
            ("apanhar", "nehmen, fangen", "Verb"),
            ("apanhar o metro", "die U-Bahn nehmen", ""),
            ("comprar", "kaufen", ""),
            ("almoçar", "zu Mittag essen", "Achtung: ç!"),
            ("tomar café", "Kaffee trinken", ""),
            ("escritório", "Büro", ""),
            ("faculdade", "Fakultät / Hochschule", ""),
        ]
    },
    "lesson-03": {
        "title": "Lesson 3 — Wochenende, Vergangenheit, Fragewörter (23.03.2026)",
        "cards": [
            ("Estou na Alemanha", "Ich bin in Deutschland", "estar + em (na)"),
            ("É difícil", "Es ist schwierig", ""),
            ("Não é fácil", "Es ist nicht einfach", ""),
            ("Como foi o seu fim de semana?", "Wie war dein Wochenende?", "Pretérito"),
            ("Foi muito difícil", "Es war sehr schwer", ""),
            ("O que tu fizeste no fim de semana?", "Was hast du am Wochenende gemacht?", "fazer im Pretérito"),
            ("No sábado eu fui ver...", "Am Samstag war ich (besichtigen)...", ""),
            ("Ontem eu saí para comer", "Gestern bin ich essen gegangen", "sair Pretérito"),
            ("Depois", "danach / später / dann", ""),
            ("Que fazes?", "Was machst du?", "Presente"),
            ("O que é que estás a fazer agora?", "Was machst du gerade?", "Verlaufsform"),
            ("Assim", "so / auf diese Weise", ""),
            ("Diverti-me", "Ich hatte Spaß", ""),
            ("Foi divertido", "Es hat Spaß gemacht", ""),
            ("Foi fixe", "Es war cool", "Slang"),
            ("Almoçar", "zu Mittag essen", ""),
            ("Jantar", "zu Abend essen / Abendessen", ""),
            ("Apanhar", "nehmen / fangen", ""),
            ("Ela é só uma amiga", "Sie ist nur eine Freundin", ""),
            ("Quem", "Wer", "Fragewort - nur Personen"),
            ("Como", "Wie", ""),
            ("Qual / Que / O que", "Welche/r / Was", ""),
            ("Quantos", "Wie viele", ""),
            ("Onde", "Wo", ""),
            ("Quando", "Wann", ""),
            ("Quanto", "Wie viel / Wie lange", ""),
            ("Qual é o gel que usas?", "Welches Gel benutzt du?", "qual = Auswahl"),
            ("Que gel é este?", "Was für ein Gel ist das?", ""),
            ("inteligente", "intelligent", ""),
            ("ambicioso", "ehrgeizig", ""),
            ("forte", "stark", ""),
            ("em forma", "in Form / fit", ""),
            ("sarado", "muskulös / sportlich (umgangssprachlich)", ""),
            ("cabelo castanho", "braune Haare", ""),
            ("olhos castanhos", "braune Augen", ""),
        ]
    },
    "lesson-04": {
        "title": "Lesson 4 — Tagesablauf, ir/vir, Beschreibungen (25.03.2026)",
        "cards": [
            ("Então", "also / dann", "Füllwort"),
            ("Eu não estou cansado", "Ich bin nicht müde", ""),
            ("Me sinto muito bem", "Ich fühle mich sehr gut", ""),
            ("Muito bem disposto", "sehr gut gelaunt", ""),
            ("Dor / Dores", "Schmerz / Schmerzen", ""),
            ("As dores passaram", "Die Schmerzen sind weg", "passar"),
            ("Direito", "gerade / rechts", ""),
            ("Diretamente", "direkt", ""),
            ("Sozinho", "allein", ""),
            ("Eu vivo sozinho", "Ich lebe allein", ""),
            ("Acordar", "aufwachen", ""),
            ("Levantar-se", "aufstehen", "reflexiv"),
            ("Começar", "anfangen", ""),
            ("Escritório", "Büro", ""),
            ("Estação", "Station / Bahnhof", ""),
            ("Estação do comboio", "Bahnhof", "PT-PT (BR: estação de trem)"),
            ("Apanhar", "nehmen / fangen", ""),
            ("Chegar", "ankommen", ""),
            ("Atrasar-se", "sich verspäten", ""),
            ("Atrasado / Atrasada", "verspätet", ""),
            ("Longe", "weit / weit weg", ""),
            ("Perto", "in der Nähe", ""),
            ("Eu janto com meus amigos", "Ich esse mit meinen Freunden zu Abend", ""),
            ("Regressar / Retornar / Voltar", "zurückkehren", "drei Synonyme"),
            ("Ir — eu vou", "gehen — ich gehe", "ir Presente"),
            ("Ir — tu vais", "du gehst", ""),
            ("Ir — ele/ela vai", "er/sie geht", ""),
            ("Ir — nós vamos", "wir gehen", ""),
            ("Ir — eles vão", "sie gehen", ""),
            ("Vir — eu venho", "kommen — ich komme", "vir Presente"),
            ("Vir — tu vens", "du kommst", ""),
            ("Vir — ele/ela vem", "er/sie kommt", ""),
            ("Vir — nós vimos", "wir kommen", ""),
            ("Vir — eles vêm", "sie kommen", ""),
            ("Estou no Brasil", "Ich bin in Brasilien", "em + o = no"),
            ("Estou na praia", "Ich bin am Strand", "em + a = na"),
            ("Estou nos hotéis de Lisboa", "Ich bin in den Hotels von Lissabon", "em + os = nos"),
            ("Alto", "groß / hoch", ""),
            ("Cabelo", "Haar", ""),
            ("Preto", "schwarz", ""),
            ("Louro / Loiro", "blond", ""),
            ("Azul", "blau", ""),
            ("Magra / Magro", "schlank", ""),
            ("Bonita / Bonito", "schön", ""),
            ("Engraçado", "lustig", ""),
            ("A casa do Paulo é bonita", "Paulos Haus ist schön", "Possessiv mit do/da"),
            ("A comida de Portugal é muito boa", "Das Essen in Portugal ist sehr gut", ""),
            ("O inverno da Alemanha é muito frio", "Der Winter in Deutschland ist sehr kalt", ""),
            ("Gordo / Gorda", "dick", ""),
            ("Magro / Magra", "dünn", ""),
            ("Careca", "Glatze / glatzköpfig", ""),
            ("Camisa", "Hemd", ""),
            ("Calças", "Hose", ""),
            ("Casaco", "Jacke / Mantel", ""),
            ("Calções", "kurze Hose", ""),
            ("Saia", "Rock", ""),
            ("Cor-de-laranja", "orange (Farbe)", ""),
            ("Cor-de-rosa", "rosa", ""),
            ("Bandeira", "Flagge", ""),
            ("Largas", "breit", ""),
            ("Saboroso", "schmackhaft", ""),
            ("Fresco", "frisch", ""),
            ("Pais", "Eltern", "Achtung: ohne Akzent!"),
            ("País", "Land", "Achtung: mit Akzent!"),
            ("Dele", "von ihm / sein", "de + ele"),
            ("Dela", "von ihr / ihr", "de + ela"),
        ]
    },
    "lesson-05": {
        "title": "Lesson 5 — Routine, estar com, Beschreibungen (01.04.2026)",
        "cards": [
            ("Estou feliz", "Ich bin glücklich", ""),
            ("Comecei uma nova rotina", "Ich habe eine neue Routine angefangen", "começar Pretérito"),
            ("Eu acordo cedo", "Ich wache früh auf", ""),
            ("Caminhada", "Spaziergang", ""),
            ("Corrida", "Lauf / Joggen", ""),
            ("Similar / Parecida", "ähnlich", ""),
            ("Acordo às 6:30", "Ich wache um 6:30 auf", "às horas"),
            ("Às vezes", "manchmal", ""),
            ("Às vezes ficamos cansados", "Manchmal werden wir müde", ""),
            ("Não tive muito tempo", "Ich hatte nicht viel Zeit", ""),
            ("Esta semana", "diese Woche", ""),
            ("Foi muito cansativo", "Es war sehr anstrengend", ""),
            ("O céu", "der Himmel", ""),
            ("Nuvens brancas", "weiße Wolken", ""),
            ("Chove", "es regnet", "chover"),
            ("Inverno", "Winter", ""),
            ("Verão", "Sommer", ""),
            ("Primavera", "Frühling", ""),
            ("Outono", "Herbst", ""),
            ("Flores amarelas", "gelbe Blumen", ""),
            ("Árvores", "Bäume", ""),
            ("Que idade tem a sua namorada?", "Wie alt ist deine Freundin?", ""),
            ("Como ela é?", "Wie ist sie?", "Beschreibung mit ser"),
            ("De que cor são os olhos dela?", "Welche Augenfarbe hat sie?", ""),
            ("Comprido", "lang", ""),
            ("Levar", "nehmen / mitnehmen", ""),
            ("Azuis", "blau (Plural)", ""),
            ("Arco-íris", "Regenbogen", ""),
            ("Estou com medo", "Ich habe Angst", "estar com + Substantiv"),
            ("Estou com fome", "Ich habe Hunger", ""),
            ("Estou com saudades", "Ich habe Sehnsucht", ""),
            ("Estou com sede", "Ich habe Durst", ""),
            ("Estou com inveja", "Ich bin neidisch", ""),
            ("Estou com vontade de", "Ich habe Lust auf", ""),
            ("Estou com calor", "Mir ist heiß", ""),
            ("Estou com sono", "Ich bin müde / schläfrig", ""),
            ("Estou com dor de dentes", "Ich habe Zahnschmerzen", ""),
            ("Estou contente", "Ich bin zufrieden / froh", "estar + Adjektiv"),
        ]
    },
    "lesson-06": {
        "title": "Lesson 6 — Essen, Routine, Vergangenheit (10.04.2026)",
        "cards": [
            ("Como foi o seu dia ontem?", "Wie war dein Tag gestern?", ""),
            ("Foi bom", "Es war gut", ""),
            ("Estava ensolarado", "Es war sonnig", "Imperfeito"),
            ("Fui tomar café", "Ich war Kaffee trinken", ""),
            ("Cozinhar", "kochen", ""),
            ("Cozinhei", "ich habe gekocht", "Pretérito"),
            ("Comi", "ich habe gegessen", "comer Pretérito"),
            ("Tu gostas de cozinhar?", "Magst du kochen?", ""),
            ("Arroz", "Reis", ""),
            ("Peixe", "Fisch", ""),
            ("Massa", "Pasta / Nudeln", ""),
            ("Carne", "Fleisch", ""),
            ("Tenho preguiça de", "Ich habe keine Lust auf", ""),
            ("Peito de frango", "Hähnchenbrust", ""),
            ("Frango", "Hähnchen", ""),
            ("Fígado", "Leber", ""),
            ("Feijão", "Bohnen", ""),
            ("Aveia", "Hafer", ""),
            ("Ovos", "Eier", ""),
            ("Cebola", "Zwiebel", ""),
            ("Alho", "Knoblauch", ""),
            ("Limão", "Zitrone", ""),
            ("Cenoura", "Karotte", ""),
            ("Temperos", "Gewürze", ""),
            ("Páprica", "Paprika (Gewürz)", ""),
            ("Folha de louro", "Lorbeerblatt", ""),
            ("Quando tu vais para Portugal?", "Wann fährst du nach Portugal?", ""),
            ("Em maio", "im Mai", ""),
            ("Último / Última", "letzte/r", ""),
            ("No último fim de semana", "letztes Wochenende", ""),
            ("Viajei", "ich bin gereist", "viajar Pretérito"),
            ("Cansativo", "anstrengend", ""),
            ("Tem / Há", "es gibt", ""),
            ("Cidade natal", "Heimatstadt", ""),
            ("Visitar", "besuchen", ""),
            ("Comida salgada", "salziges Essen", ""),
            ("Esse tipo de feijão", "diese Sorte Bohnen", ""),
            ("Principal", "Haupt-", ""),
            ("Fome", "Hunger", ""),
            ("Com fome", "hungrig", ""),
            ("Nunca", "nie", "Häufigkeit"),
            ("Sempre", "immer", ""),
            ("Às vezes", "manchmal", ""),
        ]
    },
    "lesson-07": {
        "title": "Lesson 7 — Gespräche über Wochenende, Häufigkeit (15.04.2026)",
        "cards": [
            ("Onde estavas?", "Wo warst du?", "estar Imperfeito"),
            ("Eu estava", "Ich war", "Imperfeito"),
            ("Eu fui ao médico", "Ich war beim Arzt", "ir Pretérito"),
            ("Secura na pele", "trockene Haut", ""),
            ("Eu vou", "Ich gehe", "ir Presente"),
            ("Também", "auch", ""),
            ("Comecei a escrever", "Ich habe angefangen zu schreiben", "começar a + Inf"),
            ("Mensagens", "Nachrichten", ""),
            ("Parceira de negócios", "Geschäftspartnerin", ""),
            ("O que fizeste?", "Was hast du gemacht?", "fazer Pretérito"),
            ("O que tens feito?", "Was hast du so gemacht?", "Pretérito Perfeito Composto"),
            ("Terraço", "Dachterrasse", ""),
            ("Não é bem um restaurante", "Es ist nicht wirklich ein Restaurant", ""),
            ("Nós fomos lá", "Wir gingen dorthin", "ir Pretérito"),
            ("Matraquilhos", "Tischfußball / Kicker", "PT-PT"),
            ("Ficámos lá", "Wir blieben da", "ficar Pretérito (PT-PT mit Akzent)"),
            ("Saímos", "Wir sind weggegangen", "sair Pretérito"),
            ("Não consegui acabar", "Ich konnte nicht aufessen", "conseguir Pretérito"),
            ("Eu estava muito cheio", "Ich war sehr satt", "Imperfeito"),
            ("Doce de mandioca", "Maniok-Süßspeise", ""),
            ("Eu só fiquei em casa", "Ich bin nur zu Hause geblieben", ""),
            ("Eu não saí", "Ich bin nicht rausgegangen", ""),
            ("Saí para caminhar", "Ich ging spazieren", ""),
            ("Foi tranquilo", "Es war ruhig", ""),
            ("Encontrei", "Ich traf", "encontrar Pretérito"),
            ("Almoçámos juntos", "Wir aßen zusammen zu Mittag", ""),
            ("Comemos comida alemã", "Wir aßen deutsches Essen", ""),
            ("Restaurante tradicional", "traditionelles Restaurant", ""),
            ("Eu fiz desporto", "Ich habe Sport gemacht", ""),
            ("Eu fui à sauna", "Ich war in der Sauna", ""),
            ("Subestimada", "unterschätzt", ""),
            ("Pesada", "deftig / schwer (Essen)", ""),
            ("Comida favorita", "Lieblingsessen", ""),
            ("Pequenos pepinos", "kleine Gurken", ""),
            ("Queijos", "Käse (Plural)", ""),
            ("Pão", "Brot", ""),
            ("Depois de", "nach (zeitlich)", ""),
            ("Depois desta aula", "nach dieser Stunde", ""),
            ("Ganhar", "gewinnen / verdienen", ""),
            ("Hora", "Stunde / 1 Uhr", "1 hora (Singular)"),
            ("Horas", "Stunden / Uhr (ab 2)", "São 2 horas"),
            ("Com frequência", "oft", ""),
            ("Duas a três vezes por semana", "zwei bis drei Mal pro Woche", ""),
            ("Quase", "fast", ""),
            ("Poucas vezes", "selten / wenige Male", ""),
            ("Levar", "nehmen / mitnehmen", ""),
            ("Para ti", "für dich", ""),
            ("Cultura de comer fora", "Kultur, auswärts zu essen", ""),
            ("Caro", "teuer", ""),
            ("Mistura", "Mischung", ""),
            ("Uma vez por semana", "einmal pro Woche", ""),
        ]
    },
    "lesson-08": {
        "title": "Lesson 8 — Sport, Business, Estar a + Inf, Uhrzeit (22.04.2026)",
        "cards": [
            ("O clima está muito bom", "Das Wetter ist sehr gut", ""),
            ("A temperatura está muito boa", "Die Temperatur ist sehr gut", ""),
            ("Fiz desporto hoje de manhã", "Ich habe heute Morgen Sport gemacht", ""),
            ("Infelizmente", "leider", ""),
            ("Eu também fui ao ginásio", "Ich war auch im Fitnessstudio", ""),
            ("Que tipo de treino fazes?", "Welche Art von Training machst du?", ""),
            ("Hoje treinei todo o corpo", "Heute habe ich Full-Body trainiert", ""),
            ("Ontem corri 7 quilómetros", "Gestern bin ich 7 km gelaufen", ""),
            ("Eu tento correr", "Ich versuche zu laufen", "tentar + Inf"),
            ("Duas vezes por semana", "zwei Mal pro Woche", ""),
            ("Eu gostaria", "Ich würde gerne", "Konditional"),
            ("De correr mais", "mehr zu laufen", ""),
            ("Quando começaste?", "Wann hast du angefangen?", ""),
            ("Colocar / Pôr", "setzen / legen / stellen", ""),
            ("Consistência", "Konsistenz / Beständigkeit", ""),
            ("Fator mais importante", "wichtigster Faktor", ""),
            ("Sucesso", "Erfolg", ""),
            ("Sem consistência, sem sucesso", "Ohne Konsistenz kein Erfolg", "Spruch"),
            ("Tu tens razão", "Du hast Recht", ""),
            ("Como vai o seu trabalho?", "Wie läuft deine Arbeit?", ""),
            ("Está bem", "Es geht gut", ""),
            ("Novo cliente", "neuer Kunde", ""),
            ("Tudo vai bem", "Alles läuft gut", ""),
            ("Precisamos resolver", "Wir müssen lösen", ""),
            ("Algumas coisinhas", "ein paar Kleinigkeiten", ""),
            ("Eu construí", "Ich habe gebaut", "construir Pretérito"),
            ("Aplicação", "App / Anwendung", ""),
            ("Estudar Português", "Portugiesisch lernen", ""),
            ("Está a funcionar bem", "Es funktioniert gut", "estar a + Inf"),
            ("A aplicação atende minhas necessidades", "Die App deckt meine Bedürfnisse ab", ""),
            ("Aprendizagem", "Lernen / Lernprozess", ""),
            ("Que horas são?", "Wie spät ist es?", ""),
            ("São 12 horas e 27 minutos", "Es ist 12:27 Uhr", ""),
            ("Fazer a mala", "den Koffer packen", ""),
            ("Vou viajar amanhã", "Ich werde morgen reisen", "ir + Inf = Zukunft"),
            ("Visitar um parceiro de negócios", "einen Geschäftspartner besuchen", ""),
            ("Ver o médico", "zum Arzt gehen", ""),
            ("Sessão de fotos", "Foto-Session", ""),
            ("Quero te contar uma coisa", "Ich möchte dir etwas erzählen", ""),
            ("Mudar-se", "umziehen", "reflexiv"),
            ("Um novo capítulo", "ein neues Kapitel", ""),
            ("Não há sucesso sem riscos", "Kein Erfolg ohne Risiko", ""),
            ("Principalmente", "vor allem", ""),
            ("Não tens muito a perder", "Du hast nicht viel zu verlieren", ""),
            ("Viver na vila", "in einem Dorf leben", ""),
            ("Tranquilo", "ruhig", ""),
            ("Dá-te muita energia", "Es gibt dir viel Energie", ""),
            ("Focar no que é importante", "sich auf das Wichtige konzentrieren", ""),
            ("Construíram uma casa", "sie haben ein Haus gebaut", ""),
            ("Para o meu futuro", "für meine Zukunft", ""),
            ("Quão grande?", "Wie groß?", ""),
            ("Inteligência artificial", "künstliche Intelligenz", ""),
        ]
    },
    "lesson-09": {
        "title": "Lesson 9 — Wetter, Obst, Fortschritt (29.04.2026)",
        "cards": [
            ("Tem sol", "Es scheint die Sonne", ""),
            ("Está ensolarado", "Es ist sonnig", ""),
            ("22 graus", "22 Grad", ""),
            ("Não há problema", "Kein Problem", ""),
            ("Fora", "draußen", ""),
            ("Relaxei", "Ich habe entspannt", "relaxar Pretérito"),
            ("Tinha sol", "Es war sonnig", "Imperfeito"),
            ("No domingo fiz a mesma coisa", "Am Sonntag habe ich dasselbe gemacht", ""),
            ("Na sexta-feira", "am Freitag", ""),
            ("Colega", "Kollege/in", ""),
            ("Parceiro de negócios", "Geschäftspartner", ""),
            ("Fiz fotos", "Ich habe Fotos gemacht", ""),
            ("Uso privado / pessoal", "private Nutzung", ""),
            ("Comi sushi", "Ich habe Sushi gegessen", ""),
            ("Corri fora", "Ich bin draußen gelaufen", "correr Pretérito"),
            ("Só relaxei", "Ich habe nur entspannt", ""),
            ("Caminhei / Passeei / Dei voltas", "Ich bin spazieren gegangen", ""),
            ("Na natureza", "in der Natur", ""),
            ("Num parque", "in einem Park", "em + um = num"),
            ("Numa floresta", "in einem Wald", "em + uma = numa"),
            ("Desestressar", "Stress abbauen / entspannen", ""),
            ("De novo / Novamente", "wieder / nochmal", ""),
            ("Os pais do meu amigo", "die Eltern meines Freundes", ""),
            ("Dar", "geben", ""),
            ("Eles nos deram", "Sie gaben uns", "dar Pretérito + Pronomen"),
            ("Qual fruta?", "Welche Frucht?", ""),
            ("Quais são as tuas frutas favoritas?", "Was sind deine Lieblingsfrüchte?", "quais Plural"),
            ("Graviola", "Stachelannone", "tropische Frucht"),
            ("Papaia", "Papaya", ""),
            ("Ananás", "Ananas", "PT-PT (BR: abacaxi)"),
            ("Morango", "Erdbeere", ""),
            ("Eu nunca provei", "Ich habe nie probiert", "provar Pretérito"),
            ("Quando eu vivia em Portugal", "Als ich in Portugal lebte", "Imperfeito"),
            ("Os meus dentes ficam arrepiados", "Meine Zähne werden empfindlich", ""),
            ("Época de morango", "Erdbeerzeit", ""),
            ("Delicioso", "köstlich", ""),
            ("Diretamente com produtores", "direkt vom Erzeuger", ""),
            ("O que tu achas do meu progresso?", "Was hältst du von meinem Fortschritt?", ""),
            ("Quanto mais tu tentas, mais chances tens", "Je mehr du versuchst, desto mehr Chancen hast du", "Spruch"),
            ("Eu notei", "Ich habe bemerkt", "notar Pretérito"),
            ("Estou a aprender todos os dias", "Ich lerne jeden Tag", "estar a + Inf"),
            ("Aprendo vocabulários", "Ich lerne Vokabeln", ""),
            ("Converso por mensagem", "Ich unterhalte mich per Nachricht", ""),
            ("Até agora", "bis jetzt", ""),
            ("Estou muito satisfeito", "Ich bin sehr zufrieden", ""),
            ("De não entender nada", "von nichts verstehen", ""),
            ("Para entender conversações básicas", "zu Grundkonversationen verstehen", ""),
            ("Da forma como estás a fazer", "so wie du es machst", ""),
            ("Eu acho que deves", "Ich denke, du solltest", ""),
            ("Continuar a aprender contigo", "weiter mit dir lernen", ""),
            ("Contigo", "mit dir", ""),
            ("Comigo", "mit mir", ""),
            ("Connosco / Conosco", "mit uns", "PT-PT: connosco"),
            ("Convosco", "mit euch", ""),
            ("Pouco a pouco", "Stück für Stück", ""),
            ("Vamos chegar lá", "Wir werden es schaffen", ""),
            ("Infância", "Kindheit", ""),
            ("Quando era criança", "als ich Kind war", "Imperfeito"),
            ("Rotina semanal", "Wochenroutine", ""),
            ("Durante o dia", "während des Tages", ""),
            ("Durante a semana", "während der Woche", ""),
        ]
    },
}

def write_csv(filepath, cards, lesson_label=None):
    """Schreibt CSV mit UTF-8 BOM für Mobile-Kompatibilität, Semikolon-Trenner."""
    with open(filepath, 'w', encoding='utf-8-sig', newline='') as f:
        w = csv.writer(f, delimiter=';', quotechar='"', quoting=csv.QUOTE_MINIMAL)
        w.writerow(['Portugiesisch', 'Deutsch', 'Notiz/Beispiel'])
        for pt, de, note in cards:
            full_note = f"[{lesson_label}] {note}".strip() if lesson_label and note else (lesson_label or note or '')
            w.writerow([pt, de, full_note if full_note else ''])

# Einzelne Lesson-CSVs
for key, data in LESSONS.items():
    filepath = os.path.join(OUTPUT_DIR, f"{key}.csv")
    write_csv(filepath, data['cards'])
    print(f"✓ {key}.csv ({len(data['cards'])} Karten)")

# Master-CSV mit allen Karten
all_cards = []
for key, data in LESSONS.items():
    label = key.replace('lesson-', 'L')  # L01, L02, ...
    for pt, de, note in data['cards']:
        full_note = f"[{label}] {note}".strip() if note else f"[{label}]"
        all_cards.append((pt, de, full_note))

master_path = os.path.join(OUTPUT_DIR, "alle-vokabeln.csv")
with open(master_path, 'w', encoding='utf-8-sig', newline='') as f:
    w = csv.writer(f, delimiter=';', quotechar='"', quoting=csv.QUOTE_MINIMAL)
    w.writerow(['Portugiesisch', 'Deutsch', 'Notiz/Beispiel'])
    for row in all_cards:
        w.writerow(row)

print(f"\n✓ alle-vokabeln.csv ({len(all_cards)} Karten gesamt)")

# Stats
print("\n=== Statistik ===")
total = 0
for key, data in LESSONS.items():
    n = len(data['cards'])
    total += n
    print(f"  {key}: {n} Karten")
print(f"  GESAMT: {total} Karten")
