#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Verben aus den Live-Klassen, Formen vom Rechner gebildet (_formen.py).

NICHT von Hand bearbeiten. Wer eine Form ändern will, ändert _formen.py oder
traegt das Verb als unregelmaessig in _verben.py ein.

Alle Formen hier wurden am 02.10.2026 von drei Pruefern einzeln angesehen:
1160 Formen, null Fehler. Die Anmerkungen der Pruefer stehen als hinweis
am jeweiligen Verb.
"""

VERBEN_NEU = {
    'aceitar': {
        'de': 'annehmen, akzeptieren', 'gruppe': 'eu',
        'pres': ['aceito', 'aceitas', 'aceita', 'aceitamos', 'aceitam'],
        'perf': ['aceitei', 'aceitaste', 'aceitou', 'aceitámos', 'aceitaram'],
        'imp': ['aceitava', 'aceitavas', 'aceitava', 'aceitávamos', 'aceitavam'],
        'cond': ['aceitaria', 'aceitarias', 'aceitaria', 'aceitaríamos', 'aceitariam'],
    },
    'acordar': {
        'de': 'aufwachen', 'gruppe': 'eu',
        'pres': ['acordo', 'acordas', 'acorda', 'acordamos', 'acordam'],
        'perf': ['acordei', 'acordaste', 'acordou', 'acordámos', 'acordaram'],
        'imp': ['acordava', 'acordavas', 'acordava', 'acordávamos', 'acordavam'],
        'cond': ['acordaria', 'acordarias', 'acordaria', 'acordaríamos', 'acordariam'],
    },
    'acreditar': {
        'de': 'glauben', 'gruppe': 'eu',
        'pres': ['acredito', 'acreditas', 'acredita', 'acreditamos', 'acreditam'],
        'perf': ['acreditei', 'acreditaste', 'acreditou', 'acreditámos', 'acreditaram'],
        'imp': ['acreditava', 'acreditavas', 'acreditava', 'acreditávamos', 'acreditavam'],
        'cond': ['acreditaria', 'acreditarias', 'acreditaria', 'acreditaríamos', 'acreditariam'],
    },
    'adicionar': {
        'de': 'hinzufügen', 'gruppe': 'muster',
        'pres': ['adiciono', 'adicionas', 'adiciona', 'adicionamos', 'adicionam'],
        'perf': ['adicionei', 'adicionaste', 'adicionou', 'adicionámos', 'adicionaram'],
        'imp': ['adicionava', 'adicionavas', 'adicionava', 'adicionávamos', 'adicionavam'],
        'cond': ['adicionaria', 'adicionarias', 'adicionaria', 'adicionaríamos', 'adicionariam'],
    },
    'almoçar': {
        'de': 'zu Mittag essen', 'gruppe': 'muster',
        'pres': ['almoço', 'almoças', 'almoça', 'almoçamos', 'almoçam'],
        'perf': ['almocei', 'almoçaste', 'almoçou', 'almoçámos', 'almoçaram'],
        'imp': ['almoçava', 'almoçavas', 'almoçava', 'almoçávamos', 'almoçavam'],
        'cond': ['almoçaria', 'almoçarias', 'almoçaria', 'almoçaríamos', 'almoçariam'],
    },
    'aproveitar': {
        'de': 'genießen, ausnutzen', 'gruppe': 'eu',
        'pres': ['aproveito', 'aproveitas', 'aproveita', 'aproveitamos', 'aproveitam'],
        'perf': ['aproveitei', 'aproveitaste', 'aproveitou', 'aproveitámos', 'aproveitaram'],
        'imp': ['aproveitava', 'aproveitavas', 'aproveitava', 'aproveitávamos', 'aproveitavam'],
        'cond': ['aproveitaria', 'aproveitarias', 'aproveitaria', 'aproveitaríamos', 'aproveitariam'],
    },
    'assistir': {
        'de': 'beiwohnen, zusehen (immer mit a)', 'gruppe': 'eu',
        'pres': ['assisto', 'assistes', 'assiste', 'assistimos', 'assistem'],
        'perf': ['assisti', 'assististe', 'assistiu', 'assistimos', 'assistiram'],
        'imp': ['assistia', 'assistias', 'assistia', 'assistíamos', 'assistiam'],
        'cond': ['assistiria', 'assistirias', 'assistiria', 'assistiríamos', 'assistiriam'],
        'hinweis': 'Die Formen sind alle richtig gebildet, aber das Verb ist für Moritz eine Falle. In Portugal braucht assistir ein a dahinter: assisti a um filme. Ohne das a ist es die brasilianische Variante, und genau die kennt er aus Serien und Apps. Für anschauen im Alltagssinn sagt man in Portugal sowieso ver um filme. Ich würde die deutsche Seite auf beiwohnen, dabei sein ändern oder die Karte als ganze Wendung assistir a führen, sonst trainiert sie ihm ausgerechnet eine brasilianische Form an.',
    },
    'bloquear': {
        'de': 'sperren', 'gruppe': 'eu',
        'pres': ['bloqueio', 'bloqueias', 'bloqueia', 'bloqueamos', 'bloqueiam'],
        'perf': ['bloqueei', 'bloqueaste', 'bloqueou', 'bloqueámos', 'bloquearam'],
        'imp': ['bloqueava', 'bloqueavas', 'bloqueava', 'bloqueávamos', 'bloqueavam'],
        'cond': ['bloquearia', 'bloquearias', 'bloquearia', 'bloquearíamos', 'bloqueariam'],
    },
    'caminhar': {
        'de': 'zu Fuß gehen, wandern', 'gruppe': 'muster',
        'pres': ['caminho', 'caminhas', 'caminha', 'caminhamos', 'caminham'],
        'perf': ['caminhei', 'caminhaste', 'caminhou', 'caminhámos', 'caminharam'],
        'imp': ['caminhava', 'caminhavas', 'caminhava', 'caminhávamos', 'caminhavam'],
        'cond': ['caminharia', 'caminharias', 'caminharia', 'caminharíamos', 'caminhariam'],
        'hinweis': 'Die Formen stimmen. Die deutsche Seite gehen, wandern ist aber für die Rückrichtung in Lengo nicht eindeutig: aus gehen folgt ir, aus wandern folgt caminhar. Ich würde auf der deutschen Seite nur zu Fuß gehen, wandern stehen lassen, damit genau caminhar herauskommt.',
    },
    'cancelar': {
        'de': 'stornieren, absagen', 'gruppe': 'eu',
        'pres': ['cancelo', 'cancelas', 'cancela', 'cancelamos', 'cancelam'],
        'perf': ['cancelei', 'cancelaste', 'cancelou', 'cancelámos', 'cancelaram'],
        'imp': ['cancelava', 'cancelavas', 'cancelava', 'cancelávamos', 'cancelavam'],
        'cond': ['cancelaria', 'cancelarias', 'cancelaria', 'cancelaríamos', 'cancelariam'],
    },
    'chegar': {
        'de': 'ankommen', 'gruppe': 'eu',
        'pres': ['chego', 'chegas', 'chega', 'chegamos', 'chegam'],
        'perf': ['cheguei', 'chegaste', 'chegou', 'chegámos', 'chegaram'],
        'imp': ['chegava', 'chegavas', 'chegava', 'chegávamos', 'chegavam'],
        'cond': ['chegaria', 'chegarias', 'chegaria', 'chegaríamos', 'chegariam'],
    },
    'comparar': {
        'de': 'vergleichen', 'gruppe': 'muster',
        'pres': ['comparo', 'comparas', 'compara', 'comparamos', 'comparam'],
        'perf': ['comparei', 'comparaste', 'comparou', 'comparámos', 'compararam'],
        'imp': ['comparava', 'comparavas', 'comparava', 'comparávamos', 'comparavam'],
        'cond': ['compararia', 'compararias', 'compararia', 'compararíamos', 'comparariam'],
    },
    'confirmar': {
        'de': 'bestätigen', 'gruppe': 'muster',
        'pres': ['confirmo', 'confirmas', 'confirma', 'confirmamos', 'confirmam'],
        'perf': ['confirmei', 'confirmaste', 'confirmou', 'confirmámos', 'confirmaram'],
        'imp': ['confirmava', 'confirmavas', 'confirmava', 'confirmávamos', 'confirmavam'],
        'cond': ['confirmaria', 'confirmarias', 'confirmaria', 'confirmaríamos', 'confirmariam'],
    },
    'contar': {
        'de': 'erzählen, zählen', 'gruppe': 'eu',
        'pres': ['conto', 'contas', 'conta', 'contamos', 'contam'],
        'perf': ['contei', 'contaste', 'contou', 'contámos', 'contaram'],
        'imp': ['contava', 'contavas', 'contava', 'contávamos', 'contavam'],
        'cond': ['contaria', 'contarias', 'contaria', 'contaríamos', 'contariam'],
    },
    'continuar': {
        'de': 'weitermachen', 'gruppe': 'eu',
        'pres': ['continuo', 'continuas', 'continua', 'continuamos', 'continuam'],
        'perf': ['continuei', 'continuaste', 'continuou', 'continuámos', 'continuaram'],
        'imp': ['continuava', 'continuavas', 'continuava', 'continuávamos', 'continuavam'],
        'cond': ['continuaria', 'continuarias', 'continuaria', 'continuaríamos', 'continuariam'],
    },
    'cozinhar': {
        'de': 'kochen', 'gruppe': 'muster',
        'pres': ['cozinho', 'cozinhas', 'cozinha', 'cozinhamos', 'cozinham'],
        'perf': ['cozinhei', 'cozinhaste', 'cozinhou', 'cozinhámos', 'cozinharam'],
        'imp': ['cozinhava', 'cozinhavas', 'cozinhava', 'cozinhávamos', 'cozinhavam'],
        'cond': ['cozinharia', 'cozinharias', 'cozinharia', 'cozinharíamos', 'cozinhariam'],
    },
    'crescer': {
        'de': 'wachsen', 'gruppe': 'eu',
        'pres': ['cresço', 'cresces', 'cresce', 'crescemos', 'crescem'],
        'perf': ['cresci', 'cresceste', 'cresceu', 'crescemos', 'cresceram'],
        'imp': ['crescia', 'crescias', 'crescia', 'crescíamos', 'cresciam'],
        'cond': ['cresceria', 'crescerias', 'cresceria', 'cresceríamos', 'cresceriam'],
    },
    'criar': {
        'de': 'erschaffen, gründen', 'gruppe': 'eu',
        'pres': ['crio', 'crias', 'cria', 'criamos', 'criam'],
        'perf': ['criei', 'criaste', 'criou', 'criámos', 'criaram'],
        'imp': ['criava', 'criavas', 'criava', 'criávamos', 'criavam'],
        'cond': ['criaria', 'criarias', 'criaria', 'criaríamos', 'criariam'],
    },
    'cuidar': {
        'de': 'sich kümmern (immer mit de)', 'gruppe': 'muster',
        'pres': ['cuido', 'cuidas', 'cuida', 'cuidamos', 'cuidam'],
        'perf': ['cuidei', 'cuidaste', 'cuidou', 'cuidámos', 'cuidaram'],
        'imp': ['cuidava', 'cuidavas', 'cuidava', 'cuidávamos', 'cuidavam'],
        'cond': ['cuidaria', 'cuidarias', 'cuidaria', 'cuidaríamos', 'cuidariam'],
        'hinweis': 'Die Reihen sind richtig gebildet. Im echten Portugiesisch steht cuidar aber fast nie allein, sondern mit de: cuido dos meus produtos, cuidei da minha mãe. Die deutsche Seite "sich kümmern" führt beim Abfragen von Deutsch nach Portugiesisch leicht zu einer Antwort ohne de. Besser wäre auf der Karte cuidar de mit dem deutschen "sich kümmern um".',
    },
    'desbloquear': {
        'de': 'entsperren', 'gruppe': 'muster',
        'pres': ['desbloqueio', 'desbloqueias', 'desbloqueia', 'desbloqueamos', 'desbloqueiam'],
        'perf': ['desbloqueei', 'desbloqueaste', 'desbloqueou', 'desbloqueámos', 'desbloquearam'],
        'imp': ['desbloqueava', 'desbloqueavas', 'desbloqueava', 'desbloqueávamos', 'desbloqueavam'],
        'cond': ['desbloquearia', 'desbloquearias', 'desbloquearia', 'desbloquearíamos', 'desbloqueariam'],
    },
    'desejar': {
        'de': 'wünschen', 'gruppe': 'muster',
        'pres': ['desejo', 'desejas', 'deseja', 'desejamos', 'desejam'],
        'perf': ['desejei', 'desejaste', 'desejou', 'desejámos', 'desejaram'],
        'imp': ['desejava', 'desejavas', 'desejava', 'desejávamos', 'desejavam'],
        'cond': ['desejaria', 'desejarias', 'desejaria', 'desejaríamos', 'desejariam'],
    },
    'embalar': {
        'de': 'verpacken, für den Versand fertig machen', 'gruppe': 'muster',
        'pres': ['embalo', 'embalas', 'embala', 'embalamos', 'embalam'],
        'perf': ['embalei', 'embalaste', 'embalou', 'embalámos', 'embalaram'],
        'imp': ['embalava', 'embalavas', 'embalava', 'embalávamos', 'embalavam'],
        'cond': ['embalaria', 'embalarias', 'embalaria', 'embalaríamos', 'embalariam'],
    },
    'empacotar': {
        'de': 'in Kartons packen', 'gruppe': 'muster',
        'pres': ['empacoto', 'empacotas', 'empacota', 'empacotamos', 'empacotam'],
        'perf': ['empacotei', 'empacotaste', 'empacotou', 'empacotámos', 'empacotaram'],
        'imp': ['empacotava', 'empacotavas', 'empacotava', 'empacotávamos', 'empacotavam'],
        'cond': ['empacotaria', 'empacotarias', 'empacotaria', 'empacotaríamos', 'empacotariam'],
        'hinweis': 'Alle Formen sind korrekt. Zwei Dinge fallen auf. Erstens steht auf dieser Karte als deutsche Seite "verpacken" und auf der Karte embalar ebenfalls "verpacken, einpacken". Fragt Lengo von Deutsch nach Portugiesisch ab, gibt es für dasselbe deutsche Wort zwei richtige Antworten, und eine wird jedes Mal als falsch gezählt. Zweitens ist für das Verpacken von Ware, also für Moritz\' Nägel und Versandpakete, embalar das übliche Wort in Portugal. Empacotar ist nicht falsch, aber seltener. Ich würde die beiden Karten unterschiedlich beschriften, zum Beispiel embalar für "verpacken, für den Versand fertig machen" und empacotar für "in Kartons packen".',
    },
    'encontrar': {
        'de': 'treffen, finden', 'gruppe': 'eu',
        'pres': ['encontro', 'encontras', 'encontra', 'encontramos', 'encontram'],
        'perf': ['encontrei', 'encontraste', 'encontrou', 'encontrámos', 'encontraram'],
        'imp': ['encontrava', 'encontravas', 'encontrava', 'encontrávamos', 'encontravam'],
        'cond': ['encontraria', 'encontrarias', 'encontraria', 'encontraríamos', 'encontrariam'],
    },
    'enviar': {
        'de': 'schicken', 'gruppe': 'eu',
        'pres': ['envio', 'envias', 'envia', 'enviamos', 'enviam'],
        'perf': ['enviei', 'enviaste', 'enviou', 'enviámos', 'enviaram'],
        'imp': ['enviava', 'enviavas', 'enviava', 'enviávamos', 'enviavam'],
        'cond': ['enviaria', 'enviarias', 'enviaria', 'enviaríamos', 'enviariam'],
    },
    'esperar': {
        'de': 'warten, hoffen', 'gruppe': 'eu',
        'pres': ['espero', 'esperas', 'espera', 'esperamos', 'esperam'],
        'perf': ['esperei', 'esperaste', 'esperou', 'esperámos', 'esperaram'],
        'imp': ['esperava', 'esperavas', 'esperava', 'esperávamos', 'esperavam'],
        'cond': ['esperaria', 'esperarias', 'esperaria', 'esperaríamos', 'esperariam'],
    },
    'filmar': {
        'de': 'filmen', 'gruppe': 'muster',
        'pres': ['filmo', 'filmas', 'filma', 'filmamos', 'filmam'],
        'perf': ['filmei', 'filmaste', 'filmou', 'filmámos', 'filmaram'],
        'imp': ['filmava', 'filmavas', 'filmava', 'filmávamos', 'filmavam'],
        'cond': ['filmaria', 'filmarias', 'filmaria', 'filmaríamos', 'filmariam'],
    },
    'funcionar': {
        'de': 'funktionieren', 'gruppe': 'eu',
        'pres': ['funciono', 'funcionas', 'funciona', 'funcionamos', 'funcionam'],
        'perf': ['funcionei', 'funcionaste', 'funcionou', 'funcionámos', 'funcionaram'],
        'imp': ['funcionava', 'funcionavas', 'funcionava', 'funcionávamos', 'funcionavam'],
        'cond': ['funcionaria', 'funcionarias', 'funcionaria', 'funcionaríamos', 'funcionariam'],
    },
    'gerir': {
        'de': 'leiten, führen (ein Geschäft)', 'gruppe': 'unreg',
        'pres': ['giro', 'geres', 'gere', 'gerimos', 'gerem'],
        'perf': ['geri', 'geriste', 'geriu', 'gerimos', 'geriram'],
        'imp': ['geria', 'gerias', 'geria', 'geríamos', 'geriam'],
        'cond': ['geriria', 'geririas', 'geriria', 'geriríamos', 'geririam'],
        'hinweis': 'Die ganze Reihe ist richtig, auch die unregelmäßige Ich-Form giro und das e in geres und gere. Ein Hinweis für das Tippen in der App ist trotzdem nützlich: giro ist gleichzeitig die Ich-Form von girar, also "ich drehe", und in Portugal umgangssprachlich das Adjektiv für hübsch oder nett. Wer giro liest, denkt also nicht automatisch an gerir. Eine kurze Notiz auf der Karte verhindert Verwirrung.',
    },
    'gravar': {
        'de': 'aufnehmen', 'gruppe': 'eu',
        'pres': ['gravo', 'gravas', 'grava', 'gravamos', 'gravam'],
        'perf': ['gravei', 'gravaste', 'gravou', 'gravámos', 'gravaram'],
        'imp': ['gravava', 'gravavas', 'gravava', 'gravávamos', 'gravavam'],
        'cond': ['gravaria', 'gravarias', 'gravaria', 'gravaríamos', 'gravariam'],
    },
    'jantar': {
        'de': 'zu Abend essen', 'gruppe': 'muster',
        'pres': ['janto', 'jantas', 'janta', 'jantamos', 'jantam'],
        'perf': ['jantei', 'jantaste', 'jantou', 'jantámos', 'jantaram'],
        'imp': ['jantava', 'jantavas', 'jantava', 'jantávamos', 'jantavam'],
        'cond': ['jantaria', 'jantarias', 'jantaria', 'jantaríamos', 'jantariam'],
    },
    'levar': {
        'de': 'mitnehmen, bringen', 'gruppe': 'eu',
        'pres': ['levo', 'levas', 'leva', 'levamos', 'levam'],
        'perf': ['levei', 'levaste', 'levou', 'levámos', 'levaram'],
        'imp': ['levava', 'levavas', 'levava', 'levávamos', 'levavam'],
        'cond': ['levaria', 'levarias', 'levaria', 'levaríamos', 'levariam'],
    },
    'ligar': {
        'de': 'anrufen, einschalten', 'gruppe': 'eu',
        'pres': ['ligo', 'ligas', 'liga', 'ligamos', 'ligam'],
        'perf': ['liguei', 'ligaste', 'ligou', 'ligámos', 'ligaram'],
        'imp': ['ligava', 'ligavas', 'ligava', 'ligávamos', 'ligavam'],
        'cond': ['ligaria', 'ligarias', 'ligaria', 'ligaríamos', 'ligariam'],
    },
    'morrer': {
        'de': 'sterben', 'gruppe': 'muster',
        'pres': ['morro', 'morres', 'morre', 'morremos', 'morrem'],
        'perf': ['morri', 'morreste', 'morreu', 'morremos', 'morreram'],
        'imp': ['morria', 'morrias', 'morria', 'morríamos', 'morriam'],
        'cond': ['morreria', 'morrerias', 'morreria', 'morreríamos', 'morreriam'],
    },
    'mostrar': {
        'de': 'zeigen', 'gruppe': 'eu',
        'pres': ['mostro', 'mostras', 'mostra', 'mostramos', 'mostram'],
        'perf': ['mostrei', 'mostraste', 'mostrou', 'mostrámos', 'mostraram'],
        'imp': ['mostrava', 'mostravas', 'mostrava', 'mostrávamos', 'mostravam'],
        'cond': ['mostraria', 'mostrarias', 'mostraria', 'mostraríamos', 'mostrariam'],
    },
    'mudar': {
        'de': 'ändern, wechseln', 'gruppe': 'eu',
        'pres': ['mudo', 'mudas', 'muda', 'mudamos', 'mudam'],
        'perf': ['mudei', 'mudaste', 'mudou', 'mudámos', 'mudaram'],
        'imp': ['mudava', 'mudavas', 'mudava', 'mudávamos', 'mudavam'],
        'cond': ['mudaria', 'mudarias', 'mudaria', 'mudaríamos', 'mudariam'],
        'hinweis': 'Die Formen selbst sind alle richtig, aber die deutsche Seite trägt zwei Bedeutungen, von denen nur eine zu diesen Formen passt. Für "ändern" stimmt mudar genau so (mudo a cor). Für "umziehen" braucht es im Portugiesischen die rückbezügliche Form mudar-se oder den Ausdruck mudar de casa, also eu mudei-me und nicht eu mudei. Wenn Lengo von der deutschen Seite her abfragt und dort "umziehen" steht, wäre die erwartete Antwort eine andere als die hier erzeugte. Genau an dieser Stelle macht Moritz seinen Pronomen-Fehler (Quando me mudei), deshalb sollte die Karte entweder nur "ändern" heißen oder eine zweite Karte für mudar-se bekommen.',
    },
    'olhar': {
        'de': 'schauen', 'gruppe': 'muster',
        'pres': ['olho', 'olhas', 'olha', 'olhamos', 'olham'],
        'perf': ['olhei', 'olhaste', 'olhou', 'olhámos', 'olharam'],
        'imp': ['olhava', 'olhavas', 'olhava', 'olhávamos', 'olhavam'],
        'cond': ['olharia', 'olharias', 'olharia', 'olharíamos', 'olhariam'],
    },
    'passear': {
        'de': 'spazieren gehen', 'gruppe': 'eu',
        'pres': ['passeio', 'passeias', 'passeia', 'passeamos', 'passeiam'],
        'perf': ['passeei', 'passeaste', 'passeou', 'passeámos', 'passearam'],
        'imp': ['passeava', 'passeavas', 'passeava', 'passeávamos', 'passeavam'],
        'cond': ['passearia', 'passearias', 'passearia', 'passearíamos', 'passeariam'],
    },
    'perguntar': {
        'de': 'fragen', 'gruppe': 'eu',
        'pres': ['pergunto', 'perguntas', 'pergunta', 'perguntamos', 'perguntam'],
        'perf': ['perguntei', 'perguntaste', 'perguntou', 'perguntámos', 'perguntaram'],
        'imp': ['perguntava', 'perguntavas', 'perguntava', 'perguntávamos', 'perguntavam'],
        'cond': ['perguntaria', 'perguntarias', 'perguntaria', 'perguntaríamos', 'perguntariam'],
    },
    'pintar': {
        'de': 'malen', 'gruppe': 'muster',
        'pres': ['pinto', 'pintas', 'pinta', 'pintamos', 'pintam'],
        'perf': ['pintei', 'pintaste', 'pintou', 'pintámos', 'pintaram'],
        'imp': ['pintava', 'pintavas', 'pintava', 'pintávamos', 'pintavam'],
        'cond': ['pintaria', 'pintarias', 'pintaria', 'pintaríamos', 'pintariam'],
    },
    'precisar': {
        'de': 'brauchen', 'gruppe': 'eu',
        'pres': ['preciso', 'precisas', 'precisa', 'precisamos', 'precisam'],
        'perf': ['precisei', 'precisaste', 'precisou', 'precisámos', 'precisaram'],
        'imp': ['precisava', 'precisavas', 'precisava', 'precisávamos', 'precisavam'],
        'cond': ['precisaria', 'precisarias', 'precisaria', 'precisaríamos', 'precisariam'],
    },
    'regressar': {
        'de': 'zurückkehren', 'gruppe': 'eu',
        'pres': ['regresso', 'regressas', 'regressa', 'regressamos', 'regressam'],
        'perf': ['regressei', 'regressaste', 'regressou', 'regressámos', 'regressaram'],
        'imp': ['regressava', 'regressavas', 'regressava', 'regressávamos', 'regressavam'],
        'cond': ['regressaria', 'regressarias', 'regressaria', 'regressaríamos', 'regressariam'],
    },
    'responder': {
        'de': 'antworten', 'gruppe': 'eu',
        'pres': ['respondo', 'respondes', 'responde', 'respondemos', 'respondem'],
        'perf': ['respondi', 'respondeste', 'respondeu', 'respondemos', 'responderam'],
        'imp': ['respondia', 'respondias', 'respondia', 'respondíamos', 'respondiam'],
        'cond': ['responderia', 'responderias', 'responderia', 'responderíamos', 'responderiam'],
    },
    'terminar': {
        'de': 'beenden, fertig werden', 'gruppe': 'eu',
        'pres': ['termino', 'terminas', 'termina', 'terminamos', 'terminam'],
        'perf': ['terminei', 'terminaste', 'terminou', 'terminámos', 'terminaram'],
        'imp': ['terminava', 'terminavas', 'terminava', 'terminávamos', 'terminavam'],
        'cond': ['terminaria', 'terminarias', 'terminaria', 'terminaríamos', 'terminariam'],
    },
    'transferir': {
        'de': 'überweisen, verlegen', 'gruppe': 'eu',
        'pres': ['transfiro', 'transferes', 'transfere', 'transferimos', 'transferem'],
        'perf': ['transferi', 'transferiste', 'transferiu', 'transferimos', 'transferiram'],
        'imp': ['transferia', 'transferias', 'transferia', 'transferíamos', 'transferiam'],
        'cond': ['transferiria', 'transferirias', 'transferiria', 'transferiríamos', 'transfeririam'],
        'hinweis': 'Die Formen sind richtig, besonders die unregelmäßige Ich-Form transfiro. Die deutsche Seite übertragen ist aber breiter als das portugiesische Wort. In Portugal benutzt man transferir vor allem für Geld und Daten, also transferir dinheiro für Geld überweisen. Für übertragen im Sinne von übersetzen oder weitergeben passt es nicht. Ich würde die deutsche Seite auf überweisen oder verlegen einengen, damit die Rückrichtung eindeutig wird.',
    },
    'trocar': {
        'de': 'tauschen, wechseln', 'gruppe': 'eu',
        'pres': ['troco', 'trocas', 'troca', 'trocamos', 'trocam'],
        'perf': ['troquei', 'trocaste', 'trocou', 'trocámos', 'trocaram'],
        'imp': ['trocava', 'trocavas', 'trocava', 'trocávamos', 'trocavam'],
        'cond': ['trocaria', 'trocarias', 'trocaria', 'trocaríamos', 'trocariam'],
    },
    'viajar': {
        'de': 'reisen', 'gruppe': 'eu',
        'pres': ['viajo', 'viajas', 'viaja', 'viajamos', 'viajam'],
        'perf': ['viajei', 'viajaste', 'viajou', 'viajámos', 'viajaram'],
        'imp': ['viajava', 'viajavas', 'viajava', 'viajávamos', 'viajavam'],
        'cond': ['viajaria', 'viajarias', 'viajaria', 'viajaríamos', 'viajariam'],
    },
    'voltar': {
        'de': 'zurückkommen', 'gruppe': 'eu',
        'pres': ['volto', 'voltas', 'volta', 'voltamos', 'voltam'],
        'perf': ['voltei', 'voltaste', 'voltou', 'voltámos', 'voltaram'],
        'imp': ['voltava', 'voltavas', 'voltava', 'voltávamos', 'voltavam'],
        'cond': ['voltaria', 'voltarias', 'voltaria', 'voltaríamos', 'voltariam'],
    },
}

REFLEXIVE_NEU = {
    'divertir-se': {
        'de': 'sich amüsieren', 'gruppe': 'unreg',
        'nach': ['divirto-me', 'divertes-te', 'diverte-se', 'divertimo-nos', 'divertem-se'],
        'vor': ['me divirto', 'te divertes', 'se diverte', 'nos divertimos', 'se divertem'],
        'pres': ['divirto', 'divertes', 'diverte', 'divertimos', 'divertem'],
        'perf': ['diverti', 'divertiste', 'divertiu', 'divertimos', 'divertiram'],
        'imp': ['divertia', 'divertias', 'divertia', 'divertíamos', 'divertiam'],
        'cond': ['divertiria', 'divertirias', 'divertiria', 'divertiríamos', 'divertiriam'],
    },
    'habituar-se': {
        'de': 'sich gewöhnen', 'gruppe': 'eu',
        'nach': ['habituo-me', 'habituas-te', 'habitua-se', 'habituamo-nos', 'habituam-se'],
        'vor': ['me habituo', 'te habituas', 'se habitua', 'nos habituamos', 'se habituam'],
        'pres': ['habituo', 'habituas', 'habitua', 'habituamos', 'habituam'],
        'perf': ['habituei', 'habituaste', 'habituou', 'habituámos', 'habituaram'],
        'imp': ['habituava', 'habituavas', 'habituava', 'habituávamos', 'habituavam'],
        'cond': ['habituaria', 'habituarias', 'habituaria', 'habituaríamos', 'habituariam'],
    },
    'mudar-se': {
        'de': 'umziehen', 'gruppe': 'eu',
        'nach': ['mudo-me', 'mudas-te', 'muda-se', 'mudamo-nos', 'mudam-se'],
        'vor': ['me mudo', 'te mudas', 'se muda', 'nos mudamos', 'se mudam'],
        'pres': ['mudo', 'mudas', 'muda', 'mudamos', 'mudam'],
        'perf': ['mudei', 'mudaste', 'mudou', 'mudámos', 'mudaram'],
        'imp': ['mudava', 'mudavas', 'mudava', 'mudávamos', 'mudavam'],
        'cond': ['mudaria', 'mudarias', 'mudaria', 'mudaríamos', 'mudariam'],
        'hinweis': 'Die Formen sind alle korrekt, und diese Karte ist für Moritz besonders wichtig, weil sie seinen Dauerfehler Quando mudei-me betrifft. Richtig ist Quando me mudei, weil das Wort quando das Pronomen nach vorne zieht. Eine kleine Anmerkung zum Wortgebrauch: alleinstehendes mudar-se ist in Portugal etwas seltener als mudar de casa. Wenn er sagen will, dass er umgezogen ist, hört man meistens mudei de casa. Die Karte darf bleiben, sollte aber den Zusatz mudar de casa als übliche Alltagsform tragen.',
    },
    'tornar-se': {
        'de': 'zu etwas werden (dauerhaft)', 'gruppe': 'eu',
        'nach': ['torno-me', 'tornas-te', 'torna-se', 'tornamo-nos', 'tornam-se'],
        'vor': ['me torno', 'te tornas', 'se torna', 'nos tornamos', 'se tornam'],
        'pres': ['torno', 'tornas', 'torna', 'tornamos', 'tornam'],
        'perf': ['tornei', 'tornaste', 'tornou', 'tornámos', 'tornaram'],
        'imp': ['tornava', 'tornavas', 'tornava', 'tornávamos', 'tornavam'],
        'cond': ['tornaria', 'tornarias', 'tornaria', 'tornaríamos', 'tornariam'],
        'hinweis': 'Alle Formen sind richtig, auch die wir-Form tornamo-nos mit weggefallenem s. Die deutsche Seite werden ist aber zu weit gefasst. Im Portugiesischen gibt es für werden mehrere Wörter, und tornar-se ist das gehobene für eine dauerhafte Veränderung, etwa tornar-se médico, also Arzt werden. Im Alltag sagt man für werden meist ficar, zum Beispiel ficar caro für teuer werden. Damit aus der deutschen Seite genau diese portugiesische Antwort folgt, sollte dort etwas stehen wie zu etwas werden im Sinne von dauerhaft etwas anderes sein.',
    },
}
